#%RAML 1.0
---

title: Real Time Income Information
version: 1.0
protocols: [ HTTPS ]
baseUri: https://api.service.hmrc.gov.uk/
mediaType: [ application/json, application/hal+json ]

documentation:
 - title: Overview
   content: !include documentation/overview.md
 - title: Versioning
   content: !include documentation/versioning.md
 - title: Errors
   content: !include documentation/errors.md

uses:
  sec: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/securitySchemes.raml
  headers: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/headers.raml
  annotations: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/annotations.raml

types:
  correlationId:
    pattern: "^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$"

/real-time-income-information:
  /individuals:
    /{correlationId}:
      uriParameters:
        correlationId:
          type: correlationId
          description: Identifier used to locate related transactions
      /income:
        post:
          is: [headers.acceptHeader, headers.contentHeader]
          displayName: Real Time Income Information
          description: !include documentation/overview.md
          (annotations.scope): "write:real-time-income-information"
          securedBy: [ sec.oauth_2_0: { scopes: [ "write:real-time-income-information" ] } ]
          body:
            application/json:
              type: !include schemas/real-time-income-information-post-schema.json
              example: !include examples/real-time-income-information-post.json
          responses:
            200:
              body:
                application/json:
                  type: !include schemas/real-time-income-information-response-schema.json
                  examples:
                    example-1:
                      value: !include examples/200-success-matched-one-year.json
                    example-2:
                      value: !include examples/200-success-matched-two-years.json
            400:
              body:
                application/json:
                  type: !include schemas/errors.json
                  examples:
                    invalidCorrelationId:
                      description: Invalid Correlation ID
                      value: !include examples/400-invalid-correlation-id.json
                    invalidDateRange:
                      description: Invalid Date Range
                      value: !include examples/400-invalid-date-range.json
                    invalidDatesEqual:
                      description: Invalid Dates Equal
                      value: !include examples/400-invalid-dates-equal.json
                    invalidPayload:
                      description: Invalid Payload
                      value: !include examples/400-invalid-payload.json
                    multipleErrors:
                      description: Multiple Errors
                      value: !include examples/400-multiple-errors.json
            404:
              body:
                application/json:
                  type: !include schemas/errors.json
                  examples:
                    notFound:
                      description: No data found for Nino
                      value: !include examples/404-no-data-nino.json
                    notFoundNino:
                      description: Nino cannot be found
                      value: !include examples/404-not-found-nino.json